(function(){
  'use strict';
  const C=DashboardCore,$=id=>document.getElementById(id),D=DASHBOARD;
  const memory={};let storageOK=true,busy=false,convo=[],view='today',undoAction=null,publishTimer=null,publishGeneration=0,selectedDay=C.dayKey(new Date(),TZ),showCompleted=false,activeCapture=null;
  function read(key,fallback){try{const value=localStorage.getItem('pitchford.'+key);return value?JSON.parse(value):fallback;}catch(e){storageOK=false;return memory[key]??fallback;}}
  function write(key,value){memory[key]=value;try{localStorage.setItem('pitchford.'+key,JSON.stringify(value));}catch(e){storageOK=false;$('storage-warning').hidden=false;}}
  function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  function clear(id){$(id).replaceChildren();return $(id);}
  function button(text,fn,cls='button text'){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
  const captures=read('captures.v1',[]),notes=read('study.v1',{}),sessions=read('focus-history.v1',[]);
  let timer=read('focus.v1',{duration:1200,remaining:1200,running:false,active:false});
  if(!timer||!Number.isFinite(timer.remaining)||!Number.isFinite(timer.duration))timer={duration:1200,remaining:1200,running:false,active:false};
  let course=read('course.v1',D.courses[0]?.name||'General study'),noteDay=C.dayKey(new Date(),TZ),phase={phase:'plan',item:null},heroMinutes=20;
  const dateText=(date,opts={})=>new Intl.DateTimeFormat('en-US',{timeZone:TZ,...opts}).format(new Date(date));
  function chooseView(name){view=name;document.querySelectorAll('[data-view]').forEach(b=>{const on=b.dataset.view===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});document.querySelectorAll('[role=tabpanel]').forEach(p=>p.hidden=p.id!=='view-'+name);if(name==='study'){renderKit();renderNotes();renderHistory();}if(name==='systems')renderSystems();}
  document.querySelectorAll('[data-view]').forEach(b=>{b.addEventListener('click',()=>chooseView(b.dataset.view));b.addEventListener('keydown',event=>{const all=[...document.querySelectorAll('[data-view]')];let index=all.indexOf(b);if(event.key==='ArrowRight')index=(index+1)%all.length;else if(event.key==='ArrowLeft')index=(index+all.length-1)%all.length;else if(event.key==='Home')index=0;else if(event.key==='End')index=all.length-1;else return;event.preventDefault();chooseView(all[index].dataset.view);all[index].focus();});});
  function setTheme(value){if(!['chambers','night','field'].includes(value))value='chambers';document.documentElement.dataset.theme=value;$('theme').value=value;write('theme.v1',value);}
  setTheme(read('theme.v1','chambers'));$('theme').addEventListener('change',()=>setTheme($('theme').value));
  function tick(){
    const now=new Date(),hour=Number(dateText(now,{hour:'numeric',hourCycle:'h23'}));
    $('clock').textContent=C.clock(now,TZ);$('topdate').textContent=dateText(now,{weekday:'short',month:'short',day:'numeric',year:'numeric'});
    $('greeting').textContent=(hour<12?'Good morning':hour<17?'Good afternoon':'Good evening')+', '+D.name+'.';
    phase=C.nextMove(D.deadlines,now,TZ);const item=phase.item;
    const available=phase.phase==='prepare'?Math.floor((Date.parse(item.due)-now)/60000)-2:20;heroMinutes=available>=20?20:available>=10?10:5;$('hero-focus').hidden=available<5||phase.phase==='class';$('hero-focus').textContent='Focus for '+heroMinutes+' minutes';
    const titles={prepare:'A little room before class.',class:'Keep the next question close.',reflect:'Save what you want to remember.',reset:'Give tomorrow a clear starting point.',plan:item?'Make room for what is next.':'Choose one useful thing.'};
    $('day-context').textContent=phase.phase==='class'?'Class in progress':phase.phase==='reflect'?'After class':'Your daily desk';
    $('next-label').textContent=phase.phase==='prepare'?'Before class':phase.phase==='class'?'Right now':phase.phase==='reflect'?'Close the loop':phase.phase==='reset'?'Evening reset':'Your next move';
    $('next-title').textContent=titles[phase.phase];
    $('next-detail').textContent=phase.phase==='prepare'?item.title+' starts at '+C.clock(item.due,TZ)+'. Pull your materials together and choose one question to take into the room.':phase.phase==='class'?item.title+' is on your schedule until '+C.clock(item.end,TZ)+'. Your class notes are ready.':phase.phase==='reflect'?'Capture one takeaway, one open question, and a small next step from '+item.title+'.':phase.phase==='reset'?'Review your loose ends and write down tomorrow’s first task. '+(item?'Next: '+item.title+', '+C.relativeDue(item.due,now,TZ).toLowerCase()+'.':'Your schedule has no upcoming entries.'):item?'Next: '+item.title+' · '+C.relativeDue(item.due,now,TZ)+'. Choose a manageable task for the time you have.':'There are no upcoming entries in your schedule. Capture a task or make time for a focused study block.';
    $('next-action').textContent=phase.phase==='prepare'?'Open class kit ↗':phase.phase==='class'?'Open class notes':phase.phase==='reflect'?'Write a short recap':phase.phase==='reset'?'Choose tomorrow’s first task':'Open study desk';
  }
  $('next-action').addEventListener('click',()=>{chooseView('study');if(['reflect','reset'].includes(phase.phase))$(phase.phase==='reflect'?'takeaway':'next-task').focus();});
  function weekKeys(){const today=C.dayKey(new Date(),TZ),date=new Date(today+'T12:00:00Z'),weekday=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-weekday);return Array.from({length:7},(_,i)=>{const d=new Date(date);d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);});}
  function renderWeek(){const host=clear('week');weekKeys().forEach(key=>{const d=new Date(key+'T12:00:00Z'),b=button('',()=>{selectedDay=key;renderWeek();renderAgenda();},'day');b.setAttribute('aria-pressed',String(key===selectedDay));b.setAttribute('aria-label',d.toLocaleDateString('en-US',{timeZone:'UTC',weekday:'long',month:'long',day:'numeric'}));b.append(el('span','',d.toLocaleDateString('en-US',{timeZone:'UTC',weekday:'short'})),el('strong','',String(d.getUTCDate())));if(D.deadlines.some(x=>C.dayKey(x.due,TZ)===key))b.append(el('span','dot'));host.append(b);});}
  function renderAgenda(){const now=new Date(),host=clear('agenda'),items=D.deadlines.filter(x=>C.dayKey(x.due,TZ)===selectedDay).sort((a,b)=>Date.parse(a.due)-Date.parse(b.due));$('agenda-label').textContent=selectedDay===C.dayKey(now,TZ)?'Today':new Date(selectedDay+'T12:00:00Z').toLocaleDateString('en-US',{timeZone:'UTC',weekday:'long'});if(!items.length){host.append(el('p','agenda-empty','Nothing scheduled for this day.'));return;}items.forEach(item=>{const row=el('div','agenda-row'),time=el('time','',C.clock(item.due,TZ)+(item.end?'–'+C.clock(item.end,TZ):''));time.dateTime=item.due;const detail=el('div');detail.append(el('p','',item.title));if(item.note)detail.append(el('small','',C.timeLabel(item.note)));const passed=Date.parse(item.end||item.due)<+now;if(passed)detail.append(el('small','state',item.kind==='class'?'Class time has passed':'Due time passed · completion unconfirmed'));else if(Date.parse(item.due)<=+now)detail.append(el('small','state','In progress'));row.append(time,detail);host.append(row);});}
  function renderAttention(){const host=clear('attention');$('attention-count').textContent=D.attention.length;if(!D.attention.length){const p=el('div','body');p.append(el('p','note','Nothing is waiting here. Keep loose ends in Quick capture.'));host.append(p);return;}D.attention.forEach(item=>{const card=el('article','att'),top=el('div','att-top');top.append(el('h3','',item.title));card.append(top);if(item.body)card.append(el('p','',item.body));const state=C.attentionState(item,D.deadlines,new Date(),TZ);card.append(el('span','when'+(state.past?' past':''),state.label));if(state.linked)card.append(el('p','link-note','Linked to your schedule. Clear this only after confirming completion.'));const done=button('Clear from attention',()=>mutate({name:'complete_attention',item}),'button text mutation');done.disabled=busy;card.append(done);host.append(card);});}
  function saveCaptures(){write('captures.v1',captures);renderCaptures();}
  function addCapture(text){const clean=text.trim();if(!clean)return;captures.unshift({id:crypto.randomUUID(),text:clean,created:new Date().toISOString(),done:false});saveCaptures();$('capture-state').textContent=storageOK?'Saved on this device. Nothing was published.':'Saved for this visit only; browser storage is unavailable.';}
  $('capture-form').addEventListener('submit',event=>{event.preventDefault();addCapture($('capture-input').value);$('capture-input').value='';});
  function renderCaptures(){const host=clear('captures');captures.filter(x=>showCompleted||!x.done).forEach(item=>{const li=el('li','capture-item'+(item.done?' done':''));li.append(el('p','',item.text));const actions=el('div','actions');actions.append(button(item.done?'Reopen':'Done',()=>{item.done=!item.done;saveCaptures();}));if(!item.done)actions.append(button('Add to dashboard',()=>openShare(item)));li.append(actions);host.append(li);});const count=captures.filter(x=>x.done).length;$('toggle-completed').hidden=!count;$('toggle-completed').textContent=showCompleted?'Hide completed':'Show completed ('+count+')';}
  $('toggle-completed').addEventListener('click',()=>{showCompleted=!showCompleted;renderCaptures();});
  function openShare(item){activeCapture=item;$('share-title').value=item.text.slice(0,160);$('share-body').value=item.text.length>160?item.text:'';$('share-dialog').showModal();$('share-title').focus();}
  $('share-cancel').addEventListener('click',()=>$('share-dialog').close());
  $('share-form').addEventListener('submit',async event=>{event.preventDefault();const action={name:'add_attention',item:{title:$('share-title').value.trim(),body:$('share-body').value.trim(),when:'',level:'low'}};const source=activeCapture;$('share-dialog').close();const result=await mutate(action);if(result&&source){source.shared=true;saveCaptures();$('capture-state').textContent='Added to the dashboard. Your private copy stays on this device.';}});
  function timerSave(){write('focus.v1',timer);}
  function recordSession(completed){const remaining=C.timerRemaining(timer,Date.now()),spent=Math.max(0,timer.duration-remaining);if(spent>=60||completed){sessions.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),minutes:Math.max(1,Math.round(spent/60)),course,completed});sessions.splice(60);write('focus-history.v1',sessions);}timer={duration:Number($('duration').value)*60,remaining:Number($('duration').value)*60,running:false,active:false};timerSave();renderHistory();$('timer-status').textContent=completed?'Focus block complete. Take a breath and capture your next step.':'Session ended. Any focused minutes were saved on this device.';}
  function paintTimer(){let seconds=C.timerRemaining(timer,Date.now());if(timer.active&&timer.running&&seconds===0){recordSession(true);seconds=timer.remaining;} $('timer-value').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');$('timer-label').textContent=timer.running?'Stay with one task':timer.active?'Paused':'Ready when you are';$('timer-toggle').textContent=timer.running?'Pause':timer.active?'Resume':'Start';$('timer-end').hidden=!timer.active;$('duration').disabled=timer.active;}
  function startFocus(minutes){if(timer.active){chooseView('today');$('timer-toggle').focus();$('timer-status').textContent='Your existing focus block is ready below.';return;}timer={duration:minutes*60,remaining:minutes*60,endsAt:Date.now()+minutes*60000,running:true,active:true};$('duration').value=String(minutes);timerSave();paintTimer();chooseView('today');$('timer-status').textContent='Focus started. It will survive a page refresh.';}
  $('hero-focus').addEventListener('click',()=>startFocus(heroMinutes));$('kit-focus').addEventListener('click',()=>startFocus(20));
  $('timer-toggle').addEventListener('click',()=>{if(timer.running){timer.remaining=C.timerRemaining(timer,Date.now());timer.running=false;}else{timer.endsAt=Date.now()+timer.remaining*1000;timer.running=true;timer.active=true;}timerSave();paintTimer();});
  $('timer-end').addEventListener('click',()=>{recordSession(false);paintTimer();});
  $('duration').addEventListener('change',()=>{if(!timer.active){timer.duration=timer.remaining=Number($('duration').value)*60;timerSave();paintTimer();}});
  if([300,600,1200,1500,2700].includes(timer.duration))$('duration').value=String(timer.duration/60);
  function renderHistory(){const host=clear('focus-history');const recent=sessions.filter(x=>x.course===course).slice(0,6);if(!recent.length){host.append(el('p','note','Completed focus blocks will appear here.'));return;}recent.forEach(x=>{const row=el('div','session-row',x.minutes+' minutes · '+(x.completed?'Completed':'Ended early'));row.append(el('small','',dateText(x.at,{month:'short',day:'numeric'})+' at '+C.clock(x.at,TZ)));host.append(row);});}
  function noteKey(){return course+'|'+noteDay;}
  function noteRecord(){return notes[noteKey()]||(notes[noteKey()]={course,day:noteDay,prep:'',takeaway:'',question:'',next:'',checks:[]});}
  function saveNotes(){write('study.v1',notes);const msg=storageOK?'Saved on this device at '+C.clock(new Date(),TZ):'Saved for this visit only.';$('prep-state').textContent=msg;$('reflection-state').textContent=msg;}
  function renderNotes(){const record=noteRecord();$('prep-note').value=record.prep||'';$('takeaway').value=record.takeaway||'';$('open-question').value=record.question||'';$('next-task').value=record.next||'';$('reflection-day').textContent=new Date(noteDay+'T12:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'short',day:'numeric'});const host=clear('prep-checklist');['Review the assigned reading','Choose one question for class','Keep your notes ready'].forEach((text,index)=>{const li=el('li'),label=el('label'),input=el('input');input.type='checkbox';input.checked=Boolean(record.checks?.[index]);input.addEventListener('change',()=>{record.checks=record.checks||[];record.checks[index]=input.checked;saveNotes();});label.append(input,el('span','',text));li.append(label);host.append(li);});const dates=[...new Set([C.dayKey(new Date(),TZ),...Object.values(notes).filter(x=>x.course===course).map(x=>x.day)])].sort().reverse();const selector=clear('note-day');dates.forEach(day=>{const option=el('option','',new Date(day+'T12:00Z').toLocaleDateString('en-US',{timeZone:'UTC',month:'long',day:'numeric',year:'numeric'}));option.value=day;selector.append(option);});selector.value=noteDay;}
  [['prep-note','prep'],['takeaway','takeaway'],['open-question','question'],['next-task','next']].forEach(([id,key])=>$(id).addEventListener('input',()=>{noteRecord()[key]=$(id).value;saveNotes();}));
  $('note-day').addEventListener('change',()=>{noteDay=$('note-day').value;renderNotes();});
  $('capture-next-task').addEventListener('click',()=>{const value=$('next-task').value.trim();if(!value){$('next-task').focus();return;}addCapture(value);$('reflection-state').textContent='Next step copied to your private quick captures.';});
  function renderKit(){const classes=D.deadlines.filter(x=>x.kind==='class');const candidate=phase.item?.kind==='class'?phase.item:classes.find(x=>Date.parse(x.end||x.due)>=Date.now())||classes.at(-1);$('kit-title').textContent=candidate?.title||'Your study desk';$('kit-meta').textContent=candidate?C.relativeDue(candidate.due,new Date(),TZ)+(candidate.end?'–'+C.clock(candidate.end,TZ):'')+(candidate.note?' · '+C.timeLabel(candidate.note):''):'Open your course materials and choose one useful task.';$('kit-status').textContent=candidate&&Date.parse(candidate.end||candidate.due)<Date.now()?'Most recent class':candidate&&Date.parse(candidate.due)<=Date.now()?'Current class':'Next class';if(!$('course-choice').options.length){D.courses.forEach(x=>{const option=el('option','',x.name);option.value=x.name;$('course-choice').append(option);});if(!D.courses.length){const option=el('option','','General study');option.value='General study';$('course-choice').append(option);}}if(![...$('course-choice').options].some(x=>x.value===course))course=$('course-choice').options[0].value;$('course-choice').value=course;}
  $('course-choice').addEventListener('change',()=>{course=$('course-choice').value;write('course.v1',course);noteDay=C.dayKey(new Date(),TZ);renderNotes();renderHistory();});
  $('export-notes').addEventListener('click',()=>{const blocks=Object.values(notes).filter(n=>n.prep||n.takeaway||n.question||n.next).sort((a,b)=>b.day.localeCompare(a.day)).map(n=>'# '+n.course+' · '+n.day+'\n\nBefore class\n'+(n.prep||'—')+'\n\nTakeaway\n'+(n.takeaway||'—')+'\n\nOpen question\n'+(n.question||'—')+'\n\nNext step\n'+(n.next||'—'));const blob=new Blob([blocks.join('\n\n---\n\n')||'No study notes yet.'],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='pitchford-study-notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  function sessionGet(key){try{return sessionStorage.getItem(key);}catch(e){return null;}}
  function sessionSet(key,value){try{sessionStorage.setItem(key,value);}catch(e){}}
  let pendingPass=null;
  async function getPass(){const saved=sessionGet('dashpass');if(saved)return saved;return new Promise(resolve=>{pendingPass=resolve;$('pass-input').value='';$('pass-dialog').showModal();$('pass-input').focus();});}
  $('pass-form').addEventListener('submit',event=>{event.preventDefault();const value=$('pass-input').value;if(!value)return;sessionSet('dashpass',value);$('pass-input').value='';$('pass-dialog').close();if(pendingPass){pendingPass(value);pendingPass=null;}});
  function cancelPass(){if(pendingPass){pendingPass(null);pendingPass=null;}}
  $('pass-cancel').addEventListener('click',()=>{$('pass-dialog').close();cancelPass();});$('pass-dialog').addEventListener('cancel',cancelPass);
  function busyState(value){busy=value;$('ask').disabled=value||!ASK_ENDPOINT;$('askform').querySelector('button').disabled=value||!ASK_ENDPOINT;document.querySelectorAll('.mutation').forEach(b=>b.disabled=value);$('undo').disabled=value;$('askst').textContent=value?'Working…':ASK_ENDPOINT?'Ready':'Offline';}
  function receipt(message,state='',action=null,url=null){$('receipt').hidden=false;$('receipt-message').textContent=message;$('receipt-state').textContent=state;undoAction=action;$('undo').hidden=!action;$('receipt-link').hidden=!url;if(url){try{const link=new URL(url);if(link.origin==='https://github.com'&&link.pathname.startsWith('/ppitchford02/dashboard/commit/'))$('receipt-link').href=url;else $('receipt-link').hidden=true;}catch(e){$('receipt-link').hidden=true;}}}
  $('receipt-dismiss').addEventListener('click',()=>$('receipt').hidden=true);$('undo').addEventListener('click',()=>{if(undoAction)mutate(undoAction);});
  async function request(payload){const pass=await getPass();if(!pass)return null;const response=await fetch(ASK_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},signal:AbortSignal.timeout(90000),body:JSON.stringify({...payload,pass})});const data=await response.json();if(response.status===401){try{sessionStorage.removeItem('dashpass');}catch(e){}}if(!response.ok)throw new Error(data.error||'Request failed. Try again.');sessionSet('lastAssistantSuccess',new Date().toISOString());return data;}
  function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,canonical(value[k])]));return value;}
  function waitForPublishing(expected){const generation=++publishGeneration;if(publishTimer)clearTimeout(publishTimer);let tries=0;const poll=async()=>{if(generation!==publishGeneration)return;tries++;try{const response=await fetch('data.json?verify='+Date.now(),{cache:'no-store'});if(response.ok){const data=await response.json();if(expected&&JSON.stringify(canonical(data.attention))===JSON.stringify(canonical(expected))){$('receipt-state').textContent='Published to the live dashboard.';return;}}}catch(e){}if(tries<16)publishTimer=setTimeout(poll,12000);else $('receipt-state').textContent='Saved to GitHub. Publishing is taking longer than usual; reload in a moment.';};publishTimer=setTimeout(poll,12000);}
  async function mutate(action){if(busy)return null;busyState(true);try{const data=await request({action});if(!data)return null;D.attention=data.attention;renderAttention();receipt(data.message,'Saved. The public page is updating…',data.undo,data.commit_url);waitForPublishing(data.attention);renderSystems();return data;}catch(error){receipt(error.name==='TimeoutError'?'The save result is not confirmed. Refresh before retrying.':error.message,'Your private notes remain on this device.');return null;}finally{busyState(false);}}
  function addTurn(question,answer,error=false){const turn=el('div','turn');turn.append(el('p','q','› '+question),el('p','a'+(error?' error':''),answer));$('thread').prepend(turn);return turn;}
  async function ask(question){if(busy||!ASK_ENDPOINT)return;busyState(true);try{const data=await request({question,history:convo});if(!data)return;$('ask').value='';const turn=addTurn(question,data.answer||'Done.');convo.push({role:'user',content:question},{role:'assistant',content:data.answer||'Done.'});convo=convo.slice(-10);if(data.changed){turn.append(el('p','hint','Change saved. Publishing usually takes about a minute.'));turn.append(button('Reload latest dashboard',()=>location.reload()));}renderSystems();}catch(error){addTurn(question,error.name==='TimeoutError'?'The request took too long. Check the dashboard before repeating an edit.':error.message,true);}finally{busyState(false);$('ask').focus();}}
  $('askform').addEventListener('submit',event=>{event.preventDefault();const question=$('ask').value.trim();if(question)ask(question);});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{$('ask').value=b.dataset.prompt;$('ask').focus();}));
  function renderSystems(){const host=clear('system-status');function row(title,detail,status,href){const box=el('div','system-row');box.append(el('h3','',title),el('p','',detail),el('span','system-state',status));if(href){const a=el('a','','View published run ↗');a.href=href;a.target='_blank';a.rel='noopener noreferrer';box.append(el('br'),a);}host.append(box);}row('Dashboard publishing','This page was built '+C.relativeDue(D.built_at,new Date(),TZ).toLowerCase()+'.','Refreshes automatically through GitHub Actions',D.build_url||null);const success=sessionGet('lastAssistantSuccess');row('Dashboard assistant',success?'Last successful request '+C.relativeDue(success,new Date(),TZ).toLowerCase()+'.':'No request has been verified in this browser session.',success?'Verified this session':'Ready to verify');D.agents.forEach(agent=>row(agent.name,C.timeLabel(agent.schedule),agent.status==='on'?'Enabled in saved configuration · last run unverified':agent.status==='build'?'Marked as building · execution not connected':'Disabled in saved configuration'));}
  function renderLater(){const host=clear('later');D.pending.forEach(item=>{const card=el('section','panel'),body=el('div','body');body.append(el('h2','',item.title),el('p','note',item.summary),el('span','blocker','Needs: '+item.needs));card.append(body);host.append(card);});}
  window.pickLeague=id=>{document.querySelectorAll('.league').forEach(b=>{const active=b.dataset.league===id;b.classList.toggle('sel',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-news-league]').forEach(p=>p.hidden=p.dataset.newsLeague!==id);};
  $('built-at').textContent=dateText(D.built_at,{month:'short',day:'numeric'})+' at '+C.clock(D.built_at,TZ);
  if(!storageOK)$('storage-warning').hidden=false;
  tick();renderWeek();renderAgenda();renderAttention();renderCaptures();renderKit();renderNotes();renderHistory();renderSystems();renderLater();paintTimer();chooseView('today');
  setInterval(paintTimer,1000);setInterval(()=>{const before=C.dayKey(new Date(Date.now()-30000),TZ),after=C.dayKey(new Date(),TZ);tick();renderAttention();if(before!==after){selectedDay=after;renderWeek();}renderAgenda();},30000);
  setInterval(()=>{const typing=document.activeElement?.matches('input,textarea,select');if(!busy&&!typing&&!$('ask').value&&!convo.length&&!timer.active&&!$('pass-dialog').open&&!$('share-dialog').open)location.reload();},15*60000);
})();
