(function(){
'use strict';
const $=id=>document.getElementById(id),SOURCES=[
{id:'sbd',name:'Sports Betting Dime',platform:'TikTok',url:'https://www.tiktok.com/@sportsbettingdime.com'},
{id:'bat',name:'Bat MLB Guy',platform:'TikTok',url:'https://www.tiktok.com/@_bat_mlb_guy'},
{id:'stunad',name:'Stunad Sports',platform:'Instagram',url:'https://www.instagram.com/stunadsports/'},
{id:'danny',name:'The Danny Classic',platform:'Instagram',url:'https://www.instagram.com/thedannyclassic/'},
{id:'nick',name:'Nick’s Picks',platform:'Discord',url:'https://discord.com/channels/1256750666785755296/1367550990252900392'},
{id:'cru',name:'Cru’s Picks',platform:'Discord',url:'https://discord.com/channels/1256750666785755296/1303584840909586492'}];
const MARKETS=['Home run','Moneyline','Spread','Total','Player prop','Other'],labels={pending:'Open',review:'Needs review',win:'Win',loss:'Loss',push:'Push',void:'Void'};
let request,desk={picks:[],checks:[],revisions:[]},loaded=false,busy=false,editing=null,current=null;
const source=id=>SOURCES.find(s=>s.id===id),date=s=>s?new Date(s+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date not confirmed',when=s=>s?new Date(s).toLocaleString():'Not given',signed=n=>(n>0?'+':'')+n.toFixed(2),odds=n=>n===null?'Odds not given':n>0?'+'+n:String(n);
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function note(text,error=false){$('picks-message').hidden=!text;$('picks-message').textContent=text;$('picks-message').classList.toggle('error',error);}
function syncWarning(text=''){const n=$('picks-sync-warning');n.hidden=!text;n.textContent=text;}
function parseOdds(value){const raw=value.trim();if(!raw)return null;const n=Number(raw);if(!/^[+-]?\d+$/.test(raw)||!Number.isInteger(n)||Math.abs(n)<100||Math.abs(n)>100000)throw new Error('Enter American odds such as +350 or -110, or leave blank if unknown.');return n;}
function stats(items){const active=items.filter(p=>!p.archived),eligible=active.filter(p=>p.capturedBeforeStart&&p.selection.trim()&&p.event.trim()&&p.eventDate&&p.market!=='Other'&&p.odds!==null&&Number.isInteger(p.odds)&&Math.abs(p.odds)>=100&&Math.abs(p.odds)<=100000&&['win','loss','push'].includes(p.status));const profit=eligible.reduce((n,p)=>n+(p.status==='loss'?-1:p.status==='win'?(p.odds>0?p.odds/100:100/Math.abs(p.odds)):0),0);return {open:active.filter(p=>p.status==='pending').length,review:active.filter(p=>p.status==='review').length,wins:active.filter(p=>p.status==='win').length,losses:active.filter(p=>p.status==='loss').length,eligible:eligible.length,profit,roi:eligible.length?profit/eligible.length*100:null};}
function state(value){busy=value;document.querySelectorAll('#view-picks button,#pick-dialog button,#pick-detail button').forEach(b=>b.disabled=value);}
async function load(){if(busy)return false;state(true);note('');try{const data=await request({action:'read'});if(!data)return false;desk=data;loaded=true;$('picks-content').hidden=false;$('picks-locked').hidden=true;syncWarning();render();return true;}catch(e){note(e.message,true);return false;}finally{state(false);}}
async function change(body){
  if(busy)throw new Error('Wait for the current save to finish.');
  state(true);
  try{
    const result=await request(body);
    if(!result)throw new Error('Unlock your picks to continue.');
    if(result.pick){const i=desk.picks.findIndex(p=>p.id===result.pick.id);if(i<0)desk.picks.unshift(result.pick);else desk.picks[i]=result.pick;}
    if(result.check)desk.checks.unshift(result.check);
    let refreshWarning='';
    try{
      const data=await request({action:'read'});
      if(!data)throw new Error('Sign-in was canceled.');
      desk=data;loaded=true;$('picks-content').hidden=false;$('picks-locked').hidden=true;syncWarning();
    }catch(e){refreshWarning='Saved successfully, but the full list could not refresh. Use Refresh before reviewing totals or history.';syncWarning(refreshWarning);}
    if(loaded)render();
    return refreshWarning?{...result,refreshWarning}:result;
  }finally{state(false);}
}
function render(){const sum=stats(desk.picks),host=$('picks-stats');host.replaceChildren();for(const [name,value]of[['OPEN PICKS',sum.open],['NEEDS REVIEW',sum.review],['RECORDED W–L',sum.wins+sum.losses?sum.wins+'–'+sum.losses:'—'],['1-UNIT NET RETURN',sum.eligible?signed(sum.profit)+'u':'—']]){const box=el('div','picks-stat');box.append(el('span','',name),el('strong','',String(value)));host.append(box);}renderList();const records=$('picks-records'),sources=$('picks-sources');records.replaceChildren();sources.replaceChildren();SOURCES.forEach(s=>{const st=stats(desk.picks.filter(p=>p.sourceId===s.id)),tr=el('tr');for(const text of [s.name,st.wins+'–'+st.losses,String(st.eligible),st.eligible?signed(st.profit)+'u':'—',st.roi===null?'—':signed(st.roi)+'%'])tr.append(el('td','',text));records.append(tr);const check=desk.checks.find(c=>c.sourceId===s.id),box=el('div','picks-source'),a=el('a','',s.name+' ↗');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';box.append(a,el('p','',s.platform),el('small','',check?.status||'No check recorded'));if(check)box.append(el('p','',check.note),el('p','',when(check.checkedAt)));sources.append(box);});}
function renderList(){const host=$('picks-list'),src=$('picks-source').value,sport=$('picks-sport').value,view=$('picks-view').value;host.replaceChildren();const items=desk.picks.filter(p=>(src==='all'||p.sourceId===src)&&(sport==='all'||p.sport===sport)&&(view==='archived'?p.archived:!p.archived&&(view==='open'?['pending','review'].includes(p.status):view==='review'?p.status==='review':view==='settled'?['win','loss','push','void'].includes(p.status):true)));if(!items.length){host.append(el('div','picks-empty','No picks in this view. Choose another filter or add a source entry.'));return;}items.forEach(p=>{const card=el('button','pick-card'),top=el('div','pick-card-top'),bottom=el('div','pick-card-bottom');card.type='button';top.append(el('span','',source(p.sourceId)?.name||p.sourceId),el('span','pick-state '+p.status,p.archived?'Archived':labels[p.status]));bottom.append(el('span','',odds(p.odds)),el('span','',p.capturedBeforeStart?'Captured before start':'Historical / timing unconfirmed'));card.append(top,el('h3','',p.selection||'Selection needs review'),el('p','',p.sport+' · '+p.market+' · '+(p.event||'Event not confirmed')+' · '+date(p.eventDate)),bottom);card.addEventListener('click',()=>detail(p));host.append(card);});}
function field(name){return $('pick-form').elements.namedItem(name);}
function start(p=null){editing=p;$('pick-form').reset();$('pick-form-error').textContent='';$('pick-form-title').textContent=p?'Review or correct':'Capture a pick';$('pick-form-note').textContent=p?'Original evidence is preserved. Corrections reopen the result.':'Keep the original words. Leave uncertain details blank.';const value=p||{sourceId:'sbd',sport:'MLB',market:'Home run',odds:null,postedAt:''};for(const key of ['sourceId','sport','market','selection','event','eventDate','sourceUrl','originalText'])field(key).value=value[key]||'';field('odds').value=value.odds===null?'':String(value.odds);field('postedAt').value=value.postedAt?new Date(Date.parse(value.postedAt)-new Date(value.postedAt).getTimezoneOffset()*60000).toISOString().slice(0,16):'';field('capturedBeforeStart').checked=!!value.capturedBeforeStart;field('sourceId').disabled=!!p;field('originalText').readOnly=!!p;field('sourceUrl').readOnly=!!p;$('pick-reason-field').hidden=!p;field('reason').required=!!p;$('pick-dialog').showModal();}
function detail(p){current=p;$('pick-detail-title').textContent=p.selection||'Review source entry';$('pick-detail-meta').textContent=(source(p.sourceId)?.name||p.sourceId)+' · '+p.sport+' · '+p.market+' · '+date(p.eventDate)+' · '+odds(p.odds);$('pick-evidence').textContent=p.originalText;const a=$('pick-original-link');a.hidden=!p.sourceUrl;if(p.sourceUrl)a.href=p.sourceUrl;$('pick-evidence-date').textContent='Posted: '+when(p.postedAt)+' · Captured: '+when(p.createdAt);$('pick-archive').textContent=p.archived?'Restore':'Archive';$('pick-result-form').hidden=p.archived;$('pick-outcome').value=p.status;$('pick-result-note').value=p.resultEvidence||'';$('pick-result-link').value=p.resultUrl||'';$('pick-result-error').textContent='';const history=$('pick-history');history.replaceChildren(el('p','','Created '+when(p.createdAt)+' · Version '+p.revision));desk.revisions.filter(r=>r.pickId===p.id).forEach(r=>{const d=el('details');d.append(el('summary','',r.reason+' · '+when(r.changedAt)),el('pre','',r.snapshot));history.append(d);});$('pick-detail').showModal();}
function closeDialog(id){$(id).close();$('picks-refresh').focus?.();}
function init(api){request=api;for(const s of SOURCES){for(const id of ['picks-source','pick-source']){const option=el('option','',s.name);option.value=s.id;$(id).append(option);}}for(const m of MARKETS){const option=el('option','',m);option.value=m;$('pick-market').append(option);}$('picks-unlock').addEventListener('click',load);$('picks-refresh').addEventListener('click',load);$('picks-add').addEventListener('click',()=>start());for(const id of ['picks-source','picks-sport','picks-view'])$(id).addEventListener('change',renderList);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(!busy)closeDialog(b.dataset.close);}));for(const id of ['pick-dialog','pick-detail'])$(id).addEventListener('cancel',event=>{if(busy)event.preventDefault();});
field('sport').addEventListener('change',()=>{if(field('sport').value==='NFL'&&field('market').value==='Home run')field('market').value='Player prop';});
$('pick-form').addEventListener('submit',async event=>{event.preventDefault();$('pick-form-error').textContent='';const p={};for(const key of ['sourceId','sport','market','selection','event','eventDate','sourceUrl','originalText'])p[key]=field(key).value.trim();try{p.odds=parseOdds(field('odds').value);}catch(e){$('pick-form-error').textContent=e.message;return;}p.postedAt=field('postedAt').value?new Date(field('postedAt').value).toISOString():'';p.capturedBeforeStart=field('capturedBeforeStart').checked;try{await change(editing?{action:'edit',id:editing.id,revision:editing.revision,pick:p,reason:field('reason').value}:{action:'save',pick:p});closeDialog('pick-dialog');note(editing?'Correction saved; previous evidence is kept in history.':'Source entry saved.');}catch(e){$('pick-form-error').textContent=e.message;}});
$('pick-edit').addEventListener('click',()=>{$('pick-detail').close();start(current);});$('pick-archive').addEventListener('click',async()=>{try{await change({action:'archive',id:current.id,revision:current.revision,archived:!current.archived});closeDialog('pick-detail');note(current.archived?'Pick restored.':'Pick archived. It can be restored from the Archived view.');}catch(e){$('pick-result-error').textContent=e.message;note(e.message,true);}});
$('pick-result-form').addEventListener('submit',async event=>{event.preventDefault();try{await change({action:'settle',id:current.id,revision:current.revision,status:$('pick-outcome').value,resultEvidence:$('pick-result-note').value,resultUrl:$('pick-result-link').value});closeDialog('pick-detail');note('Result saved.');}catch(e){$('pick-result-error').textContent=e.message;}});
const mc=document.modelContext||navigator.modelContext;if(mc){const add=(name,description,inputSchema,execute,readOnly=false)=>{Promise.resolve(mc.registerTool({name,description,inputSchema,annotations:{readOnlyHint:readOnly},execute})).catch(()=>{});};const prop={type:'object',properties:{}};add('dashboard_picks_read','Read private picks and source checks from the integrated Sports Picks dashboard tab. Requires existing dashboard passphrase sign-in.',prop,async()=>{if(!await load())throw new Error('Could not read fresh picks. Unlock Sports Picks or check the connection and try again.');return JSON.stringify({sources:SOURCES,...desk});},true);const properties={sourceId:{type:'string',enum:SOURCES.map(s=>s.id)},sport:{type:'string',enum:['MLB','NFL']},market:{type:'string',enum:MARKETS},selection:{type:'string'},event:{type:'string'},eventDate:{type:'string'},odds:{type:['integer','null']},postedAt:{type:'string'},sourceUrl:{type:'string'},originalText:{type:'string'},capturedBeforeStart:{type:'boolean'}};add('dashboard_picks_capture','Save one original source pick or unresolved caption to the private dashboard. Never invent odds, selection, event, or date. Unknown fields empty, odds null. Historical/uncertain timing must use capturedBeforeStart=false. Places no bet.',{type:'object',properties,required:Object.keys(properties),additionalProperties:false},async p=>JSON.stringify(await change({action:'save',pick:p})));add('dashboard_picks_source_check','Record an actual check of a configured source, including extraction or access blockers.',{type:'object',properties:{sourceId:properties.sourceId,status:{type:'string',enum:['Checked','No new posts','Sign-in needed','Access blocked','Needs review']},note:{type:'string'}},required:['sourceId','status','note']},async p=>JSON.stringify(await change({action:'check',...p})));add('dashboard_picks_import','Import Preston’s existing Picks Desk records into his integrated private dashboard, preserving original IDs, timestamps, and history. Only use for the user-authorized migration; never fabricate imported records.',{type:'object',properties:{desk:{type:'object',properties:{picks:{type:'array',items:{type:'object'}},checks:{type:'array',items:{type:'object'}},revisions:{type:'array',items:{type:'object'}}},required:['picks','checks','revisions']}},required:['desk']},async p=>JSON.stringify(await change({action:'import',desk:p.desk})));}
}
window.PitchfordPicks={init,open:()=>{if(loaded)render();},stats};
})();
